name: Release CI

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Install
        run: |
          sudo apt-get install zip
          sudo apt-get install build-essential
      - name: Build
        run: |
          make
          cd build
          zip program.zip main test
      - name: Run The Test
        run: make check
      - name: Run The Program
        run: make EXP='\(1+\(2\)\)' run
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@v1.1.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Latest Version
          files: build/program.zip